name: langgraph-redis-notebooks
services:
  jupyter:
    build:
      context: .  # Build from current directory
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jupyter/workspace/examples
      - ../:/home/jupyter/workspace/langgraph-checkpoint-redis
    environment:
      - REDIS_URL=redis://redis:6379
      - USER_AGENT=LangGraphRedisJupyterNotebooks/0.0.4
    user: jupyter
    working_dir: /home/jupyter/workspace/examples
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"