name: langgraph-redis-notebooks
services:
  jupyter:
    build:
      context: ../../..  # This should point to the root of langgraph-redis
      dockerfile: libs/checkpoint-redis/examples/Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jupyter/workspace/libs/checkpoint-redis/examples
    environment:
      - REDIS_URL=redis://redis:6379
      - USER_AGENT=LangGraphRedisJupyterNotebooks/0.0.4
    user: jupyter
    working_dir: /home/jupyter/workspace/libs/checkpoint-redis/examples
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"